### ISSUE TITLE
Map Dots

### ISSUE THREAD

**Issue by Guess1m** [Guess1m/ReportsPlus#47]
![image](https://github.com/Guess1m/ReportsPlus/assets/24523538/bc2cfda1-77bf-4a2e-8c1a-22796f45068e)

**Comment by thephilluk** [comment]
Also this: https://discord.com/channels/1248997145491804240/1267213989499109448
> Street name and cross street as well with area and county shows up on the RP+ map when user does a traffic stop.
For pursuit, it will show the original starting point of the pursuit ended with street name or location of that area

> For an example on pursuit. Say the user start the pursuit at Great Ocean Hwy, Paleto Bay (Area), Los Angeles (San Andreas) county and the Sandy Shore... The map would be like a dot at the starting part with the location, area, county and end at Sandy Shore location, area, county.
